<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

// Provide a named route for password reset links generated by the
// framework notifications. This redirects to a frontend reset page
// (set `FRONTEND_URL` in .env) so the email link doesn't fail.
Route::get('password/reset/{token}', function (Request $request, $token) {
    $frontend = env('FRONTEND_URL', 'http://localhost:3000');
    $email = $request->query('email');
    $url = $frontend . '/reset-password?token=' . $token . ($email ? '&email=' . urlencode($email) : '');
    return redirect()->to($url);
})->name('password.reset');
